import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationBarServer } from "./components/NavigationBarServer";
import { LoaderProvider } from "./context/LoaderContext";
import { NotificationProvider } from "./context/Notification";
import Loader from "./components/Loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LoaderProvider>
      <NotificationProvider>
        <html
          lang="en"
          className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
          <body className="flex min-h-screen">
            <NavigationBarServer />       {/* width: 220px — tự chiếm chỗ */}
            <Loader/>
            <main className="flex-1">    {/* flex-1 — tự lấp đầy phần còn lại */}
              {children}
            </main>
          </body>
        </html>
      </NotificationProvider>
    </LoaderProvider>
  );
}
